[package]
name = "torch2424/wasm-matrix"
version = "0.0.2"
description = "A Matrix effect in your terminal using AssemblyScript ðŸš€ and WASI ðŸ§© . Deployed to WAPM ðŸ“¦ ."
readme = "README.md"
repository = "https://github.com/torch2424/wasm-matrix"

[[module]]
name = "wasm-matrix"
source = "build/optimized.wasm"
abi = "none"

[[command]]
name = "wasm-matrix"
module = "wasm-matrix"
